# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Build:
    runs-on: self-hosted
    steps:
      - name: "Checkout project from repo"
        uses: actions/checkout@v2
      - name: "Building project - Unit tests"
        uses: xlui/action-maven-cli@jdk11
        with:
          lifecycle: 'clean package test site'
      - name: "Archiving unit test results as artifact"
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-results
          path: /home/vagrant/runner-rest/actions-runner/_work/rest-service/rest-service/target/site
      - name: "Publishing html reports"
        run: "export DATE=$(date +%s); cp -R /home/vagrant/runner-rest/actions-runner/_work/rest-service/rest-service/target/site \"/var/www//html/${DATE}\"; echo \"http://localhost:8080/${DATE}\"; echo \"::notice:: this is a notice: http://localhost:8080/${DATE}\" "
      - name: "LS Surefire folder"
        run: "ls /home/vagrant/runner-rest/actions-runner/_work/rest-service/rest-service/target/surefire-reports/"
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "/home/vagrant/runner-rest/actions-runner/_work/rest-service/rest-service/target/surefire-reports/*.xml"
          
      - name: "Sonar Scan"
        uses: xlui/action-maven-cli@jdk11
        with:
          lifecycle: ' -X sonar:sonar -Dsonar.host.url=http://sonarqube.sd.astrazeneca.com -Dmaven.test.failure.ignore=true -Dsonar.login=db8faa899a39f6435519bf6afad31f6e99b465a2'
      
    


